# Site settings
email: gaz_williams@hotmail.com
description: >
url: "http://www.gcwilliams.co.uk"
baseurl: "" 
github_username:  gcwilliams

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed
excerpt_separator: <!--more-->